apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: expense
      app.kubernetes.io/component: expense
      app.kubernetes.io/instance: expense
    name: expense
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: expense
    strategy: {}
    template:
      metadata:
        labels:
          deployment: expense
      spec:
        containers:
        - image: quay.io/redhattraining/ocpdev-expense-service-health:4.12
          name: expense
          ports:
          - containerPort: 8080
            protocol: TCP
          - containerPort: 8443
            protocol: TCP
            resources:
              requests:
                memory: "100Mi"
              limits:
                memory: "100Mi"
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: expense
      app.kubernetes.io/component: expense
      app.kubernetes.io/instance: expense
    name: expense
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: 8443-tcp
      port: 8443
      protocol: TCP
      targetPort: 8443
    selector:
      deployment: expense
  status:
    loadBalancer: {}
kind: List
metadata: {}
